[project]
name = 'lc-smartcontract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.boltproto-sbtc]
path = 'contracts/boltproto-sbtc.clar'
clarity_version = 3
epoch = 3.1

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 3
epoch = 3.1

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.token-usdh]
path = 'contracts/token-usdh.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
